image: docker.vokal.io/web-testing
build:
  image: registry.vokal.io/web-testing
  environment:
    - REPO_OWNER=vokal
    - REPO_NAME=cvr
  commands:
    - npm install --silent -g istanbul
    - npm install --silent
    - chmod +x run-build.sh
    - ./run-build.sh
